<h1 style="color:#081c15"><b>Pandas Data Frame</b></h1>
<hr style="color:#081c15">

<h4 style="color:#081c15"><b>Pandas Data Frame</b></h4>

 - A Pandas data frame is like a table. It is a 2-D array holding data of any type.

In [158]:
import pandas as pd
import numpy as np


<h4 style="color:#081c15"><b>Make Pandas Dataframe Using Python Differnt Objects</b></h4>

<ul style="color:red"><li><b>Using List</b></li></ul>

In [159]:
studentsList=[[100,20,145],[90,22,113],[71,18,180],[32,27,110]]
df=pd.DataFrame(studentsList,columns=['marks','age','iq'])
df

   marks  age   iq
0    100   20  145
1     90   22  113
2     71   18  180
3     32   27  110

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

In [160]:
studentsDict={
    'name':['Tayyab','Ali','Ahmad','Bisma'],
    'marks':[100,90,71,32],
    'age':[20,18,22,25]
}

df=pd.DataFrame(studentsDict)
df

     name  marks  age
0  Tayyab    100   20
1     Ali     90   18
2   Ahmad     71   22
3   Bisma     32   25

<ul style="color:red"><li><b>Using CSV File</b></li></ul>

In [161]:
movies=pd.read_csv("movies.csv")
# movies
ipl=pd.read_csv("ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

<h4 style="color:#081c15"><b>Dataframe Attributes</b></h4>

<ul style="color:red"><li><b>shape</b></li></ul>

In [162]:
movies.shape

(1629, 18)

<ul style="color:red"><li><b>dtypes</b></li></ul>

In [163]:
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

<ul style="color:red"><li><b>index</b></li></ul>

In [164]:
movies.index

RangeIndex(start=0, stop=1629, step=1)

<ul style="color:red"><li><b>columns</b></li></ul>

In [165]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

<ul style="color:red"><li><b>values</b></li></ul>

In [166]:
movies.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

<h4 style="color:#081c15"><b>Dataframe Methods</b></h4>

<ul style="color:red"><li><b>head</b></li></ul>

In [167]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

<ul style="color:red"><li><b>tail</b></li></ul>

In [168]:
movies.tail()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

<ul style="color:red"><li><b>sample</b></li></ul>

In [169]:
movies.sample(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
237,Rukh (film),tt7341406,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rukh_(film),Rukh,Rukh,0,2017,106,Drama|Mystery,6.4,383,Away from home in a boarding school 18-year-o...,After his father dies in a car accident a boy...,NaN,Manoj Bajpayee|Smita Tambe|Adarsh Gourav|Subhr...,NaN,27 October 2017 (India)
1154,Aryan: Unbreakable,tt0454396,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aryan:_Unbreakable,Aryan: Unbreakable,Aryan: Unbreakable,0,2006,135,Action|Drama|Sport,4.5,283,Aryan a boxer and his coach Ranvir Singh. Ar...,Aryan a young boxer gives up the sport after...,NaN,Sohail Khan|Sneha Ullal|Inder Kumar|Farida Jal...,NaN,15 December 2006 (India)

<ul style="color:red"><li><b>info</b></li></ul>

In [170]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

<ul style="color:red"><li><b>describe</b></li></ul>

In [171]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

<ul style="color:red"><li><b>isnull</b></li></ul>

In [172]:
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

<ul style="color:red"><li><b>duplicated</b></li></ul>

In [173]:
movies.duplicated().sum()

0

<ul style="color:red"><li><b>rename</b></li></ul>

In [174]:
movies.rename(columns={'wins_nominations':'wins_Nomination','runtime':'runTime'},inplace=True)

<ul style="color:red"><li><b>astype</b></li></ul>

In [175]:
movies['is_adult']=movies['is_adult'].astype('bool')
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title_x          1629 non-null   object
 1   imdb_id          1629 non-null   object
 2   poster_path      1526 non-null   object
 3   wiki_link        1629 non-null   object
 4   title_y          1629 non-null   object
 5   original_title   1629 non-null   object
 6   is_adult         1629 non-null   bool
 7   year_of_release  1629 non-null   int64
 8   runTime          1629 non-null   object
 9   genres           1629 non-null   object
 10  imdb_rating      1629 non-null   float64
 11  imdb_votes       1629 non-null   int64
 12  story            1609 non-null   object
 13  summary          1629 non-null   object
 14  tagline          557 non-null    object
 15  actors           1624 non-null   object
 16  wins_Nomination  707 non-null    object
 17  release_date     1522 non-null   object
dtypes: bool(1), float64(1), int64(2), object(14)
memory usage: 218.1+ KB

<h4 style="color:#081c15"><b>Other Dataframe Important work</b></h4>

<ul style="color:red"><li><b>Selection of a Single column</b></li></ul>

In [176]:
movies['actors']

0       Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1       Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2       Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3       Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4       Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
                              ...
1624    Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625    Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626    Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                            Gippy Grewal|Zareen Khan|
1628                                          Fawad Khan|
Name: actors, Length: 1629, dtype: object

<ul style="color:red"><li><b>Selection of multiple columns</b></li></ul>

In [177]:
movies[['actors','runTime']]

                                                 actors runTime
0     Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...     138
1     Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...     131
2     Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...     112
3     Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...     121
4     Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...     102
...                                                 ...     ...
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...     148
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...     146
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...      \N
1627                          Gippy Grewal|Zareen Khan|     136
1628                                        Fawad Khan|      35

[1629 rows x 2 columns]

<ul style="color:red"><li><b>Selection of a single row</b></li></ul>

In [178]:
movies.iloc[0]

title_x                                     Uri: The Surgical Strike
imdb_id                                                    tt8291224
poster_path        https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link          https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                     Uri: The Surgical Strike
original_title                              Uri: The Surgical Strike
is_adult                                                       False
year_of_release                                                 2019
runTime                                                          138
genres                                              Action|Drama|War
imdb_rating                                                      8.4
imdb_votes                                                     35112
story              Divided over five chapters  the film chronicle...
summary            Indian army special forces execute a covert op...
tagline                                                          NaN
actors             Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_Nomination                                               4 wins
release_date                                   11 January 2019 (USA)
Name: 0, dtype: object

In [179]:
# Another method
movies.loc[0:50:20]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runTime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_Nomination,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,False,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
20,Mere Pyare Prime Minister,tt8207768,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Pyare_Prime...,Mere Pyare Prime Minister,Mere Pyare Prime Minister,False,2018,104,Drama,6.8,344,A story about four children living in a Mumbai...,A story about four children living in a Mumbai...,Meri Ek Arzi Sun Lo Zara,Rasika Agashe|Sonia Albizuri|Syna Anand|Adarsh...,NaN,15 March 2019 (India)
40,Super 30 (film),tt7485048,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Super_30_(film),Super 30,Super 30,False,2019,154,Biography|Drama,8.2,13972,Anand Kumar a Mathematics genius from a modes...,Based on life of Patna-based mathematician Ana...,Inspired by the Life of Anand Kumar & His Stud...,Hrithik Roshan|Mrunal Thakur|Nandish Singh|Vir...,NaN,12 July 2019 (USA)

<ul style="color:red"><li><b>Selection of multiple rows</b></li></ul>

In [180]:
movies.iloc[0:5:2] # third paramter is for steps
movies.iloc[[0,2,9]] # third paramter is for steps

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runTime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_Nomination,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,False,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,False,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
9,Thackeray (film),tt7777196,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thackeray_(film),Thackeray,Thackeray,False,2019,120,Biography|Drama,5.1,2301,Balasaheb Thackrey works as a cartoonist for a...,Biographical account of Shiv Sena Supremo Bal...,NaN,Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...,NaN,25 January 2019 (India)

<ul style="color:red"><li><b>Selection of multiple rows and columns</b></li></ul>

In [181]:
movies.iloc[0:5,0:2]      
# While using iloc We always provide index of columns and slicing last part is excluded
movies.loc[0:5,['title_x','imdb_id']]
# While using loc We can provide index of columns  and name of columns as well while slicing last part is included

                                title_x    imdb_id
0              Uri: The Surgical Strike  tt8291224
1                         Battalion 609  tt9472208
2  The Accidental Prime Minister (film)  tt6986710
3                       Why Cheat India  tt8108208
4                       Evening Shadows  tt6028796
5                           Soni (film)  tt6078866

<ul style="color:red"><li><b>Adding of New Columns</b></li></ul>

In [182]:
ipl['country']='india'

<h4 style="color:#081c15"><b>Data Filtering</b></h4>

<ul style="color:red"><li><b>Find all the final winners</b></li></ul>

In [183]:
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,country
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,india
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,india

In [184]:
# index=ipl['MatchNumber']=='Final'
# winners=ipl[index]
# winners[['Season','WinningTeam']]


# other metod
ipl[ipl['MatchNumber']=='Final'][['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

<ul style="color:red"><li><b>How many super over finishes have occured</b></li></ul>

In [185]:
ipl[ipl['SuperOver']=='Y'].shape[0]

14

<ul style="color:red"><li><b>How many matches has csk won in kolkata</b></li></ul>

In [186]:
ipl[(ipl['City']=='Kolkata') & (ipl['WinningTeam']=='Chennai Super Kings')].shape[0]

5

<ul style="color:red"><li><b>Toss winner is match winner in percentage</b></li></ul>

In [187]:
ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0] / ipl.shape[0]*100

51.473684210526315

<ul style="color:red"><li><b>Movies with rating higher than 8 and votes>10000</b></li></ul>

In [188]:
movies[(movies['imdb_rating']>8.0) & (movies['imdb_votes']>10000)].shape[0]

43

<ul style="color:red"><li><b>Action movies with rating higher than 7.5</b></li></ul>

In [189]:
# movies[(movies['genres'].str.contains('Action')) & (movies['imdb_rating']>7.5)].shape[0]
#other way
movies[(movies['genres'].str.split('|').apply(lambda x:'Action' in x)) & (movies['imdb_rating']>7.5)].shape[0]

33

<ul style="color:red"><li><b>Write a function that can return the track record of 2 teams against each other</b></li></ul>

In [190]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,country
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,india
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,india
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,india
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,india
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,india
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,...,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,india
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,...,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,india
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,...,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,india
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,india
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,india

In [191]:
def teams2Winners(x,y):
    count1=movies[movies['WinningTeam']==x].shape[0]
    count2=movies[movies['WinningTeam']==y].shape[0]
    return (count1,count2)
   
   
ipl 

hello=teams2Winners('Rajasthan Royals','Gujarat Titans')

KeyError: 'WinningTeam'

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>U</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>

<ul style="color:red"><li><b>Using Dictionary</b></li></ul>